version: 2.1

jobs:
  build_and_publish:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true
    working_directory: ~/docker-kubectl
    steps:
      - checkout
      - run:
          name: Login to Docker Hub
          command: echo "$DOCKER_PASS" | docker login -u $DOCKER_USER --password-stdin
      - run:
          name: Build image
          command: |
            export KUBECTL_VERSION=${CIRCLE_TAG:-v1.18.3}
            docker build --build-arg VERSION=${KUBECTL_VERSION} -t verdigristech/kubectl:${KUBECTL_VERSION} .
            ([ -n "${CIRCLE_TAG}" ] && docker tag verdigristech/kubectl:${KUBECTL_VERSION} verdigristech/kubectl:latest) || true
      - run:
          name: Publish to Docker Hub
          command: |
            export KUBECTL_VERSION=${CIRCLE_TAG:-v1.18.3}
            docker push verdigristech/kubectl:${KUBECTL_VERSION}
            ([ -n "${CIRCLE_TAG}" ] && docker push verdigristech/kubectl:latest) || true

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build_and_publish:
          context: common
          filters:
            tags:
              only: /v\d+(\.\d+)*/
